//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Ajiejoy @ajiejoy
//

import UIKit

class ___VARIABLE_productName:identifier___Interactor {

    weak var presenter: ___VARIABLE_productName:identifier___PresenterProtocol?
    
}

//MARK: - ___VARIABLE_productName:identifier___InteractorProtocol

extension ___VARIABLE_productName:identifier___Interactor: ___VARIABLE_productName:identifier___InteractorProtocol {
    
}
