//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Ajiejoy @ajiejoy
//

import UIKit

class ___VARIABLE_productName:identifier___ViewController: UIViewController {

    //MARK:- Properties
    
	var presenter: ___VARIABLE_productName:identifier___PresenterProtocol!

    
    //MARK:- Initial
    
    init(){
        super.init(nibName: nil, bundle: nil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    //MARK:- View Lifecycle
    
	override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }

    func setupUI(){
        
    }
}


//MARK: - ___VARIABLE_productName:identifier___ViewProtocol

extension ___VARIABLE_productName:identifier___ViewController : ___VARIABLE_productName:identifier___ViewProtocol {
    
}
